Remnev Aleksandr
introduction-to-python-2021-1/PythonFinalTask pull request #3
Opened 2021-05-07 08:05 UTC by SorryLegacy

2021-05-09 15:24 UTC, Shurke commented
К сожалению, не работает.
![Remnev Aleksandr](https://user-images.githubusercontent.com/44495358/117577739-bbd87a00-b0f3-11eb-8042-c98573c43aa8.png)

2021-05-10 08:57 UTC, Shurke commented
Все еще не работает.
![Screenshot from 2021-05-10 11-56-36](https://user-images.githubusercontent.com/44495358/117633559-d3147780-b186-11eb-89b1-cc6eaf14de1b.png)

2021-05-11 15:49 UTC, Shurke commented
Пока что ситуация не изменилась.
![Screenshot from 2021-05-11 18-49-08](https://user-images.githubusercontent.com/44495358/117845892-9c735580-b289-11eb-9638-0d5bef921b9e.png)

2021-05-12 17:01 UTC, Shurke reviewed
Опция `--json` не работает как таковая.
![Screenshot from 2021-05-12 19-47-00](https://user-images.githubusercontent.com/44495358/118013655-03ad0a80-b35b-11eb-9c98-4b17e4ff7d7b.png)

2021-05-12 17:01 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.limit <= 0:
Если передать в rss_reader в качестве аргумента пустую строку, то наблюдаем очень некрасивую картину.
![Screenshot from 2021-05-12 19-42-32](https://user-images.githubusercontent.com/44495358/118012893-360a3800-b35a-11eb-9e61-46a6017d4b36.png)

2021-05-12 17:01 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.limit <= 0:
Если выполнить `rss_reader.py "https://news.yahoo.com/rss/"`, то rss_reader снова отказывается работать. В моем понимании - это очень странно, что программа без лимита ломается.
![Screenshot from 2021-05-12 19-44-20](https://user-images.githubusercontent.com/44495358/118013190-85506880-b35a-11eb-9198-7c152f5fd261.png)

2021-05-12 17:01 UTC, Shurke commented on .travis.yml
> +
Обновите свой форк до актуальной версии репозитрия.

2021-05-12 17:01 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    # create positional and optional arguments
Докстринга обычно пишется таким образом.
```python
def create_parser(args):
    """Create positional and optional arguments"""
```

2021-05-12 17:01 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        sys.exit()
Очень бедный хендлинг исключений.
Можно предусмотреть обилие различных сообщний для пользователя: страница не найдена, неверный урл и всякое такое.

2021-05-12 17:01 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +                break
Этот кусок когда повторяется и в строках 63-64.
И хочу сказать, что это несколько грубый и топорный способ реализации лимита.
На мой вгзляд, то проще и изящнее это сделать в 47 строке. Я думаю, что `feed["items"]` - это список или кортеж, а следовательно можно использовать срезы.
Подумайте над этим.

2021-05-12 17:01 UTC, Shurke commented on tests/test.py
> +import sys
Импорты должны быть сгруппированы в следующем порядке:

1. импорты из стандартной библиотеки
2. импорты сторонних библиотек
3. импорты модулей текущего проекта

Вставляйте пустую строку между каждой группой импортов.

2021-05-12 17:01 UTC, Shurke commented on tests/test.py
> +        def test_limit(self):
Добавьте к каждому тесту строку документации, чтобы было понятно, что проверяется в тесте.

2021-05-12 17:01 UTC, Shurke commented on tests/test.py
> +import rss_reader as RR
Начну с того, что это не по РЕР8.
Да и в принципе на этом заканчу.
rss_reader не слишком длинное название (учитывая длинну строки 120 символов), чтобы вводить какое-то сокращение.

2021-05-12 17:01 UTC, Shurke commented on tests/test.py
> +            self.assertTrue(RR.open_url(parser.url))
При этом я не вижу теста, что приложение не упадет, если вызвать rss_reader без лимита.

2021-05-12 17:01 UTC, Shurke commented on tests/test.py
> +            self.assertTrue(parser.json)
И в тоже время `--json` не работает.

2021-05-15 08:07 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.limit <= 0:
В общем и целом, все также пустая строка вызывает падение программы.
![Screenshot from 2021-05-15 11-03-18](https://user-images.githubusercontent.com/44495358/118353132-aa68f500-b56d-11eb-8808-0c7f875ec94a.png)

2021-05-15 08:08 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.limit <= 0:
Исправлено.

2021-05-15 08:09 UTC, Shurke commented
> Опция `--json` не работает как таковая.

Тут также ничего не изменилось.
![Screenshot from 2021-05-15 11-04-23](https://user-images.githubusercontent.com/44495358/118353218-fae05280-b56d-11eb-980d-226fb2aec5bb.png)

2021-05-15 08:11 UTC, Shurke commented
Неверный url приводит к падению ридера.
![Screenshot from 2021-05-15 11-05-23](https://user-images.githubusercontent.com/44495358/118353280-3da22a80-b56e-11eb-9340-dda5107e90c2.png)

2021-05-15 08:13 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        sys.exit()
Ситуация не изменилась. 
И как видем, хватает случаев, когда ридер падает и не обрабатывает исключения.

2021-05-15 08:16 UTC, Shurke commented
Лимит = 0 ничего не выводит на экран.
Отрицательный лимит приводит к тому, что выкидываются все новости.
Было бы вполне логичным добавить обработку невалидных лимитов.
![Screenshot from 2021-05-15 11-15-21](https://user-images.githubusercontent.com/44495358/118353438-dafd5e80-b56e-11eb-8b73-cd9451beb440.png)

2021-05-15 08:17 UTC, Shurke commented on tests/test.py
> +        def test_limit(self):
Замечание было проигнорировано.

2021-05-15 08:21 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    """create positional and optional arguments"""
У вас в функция в строках документации почему-то применяется разный стиль. Так не должно быть.

2021-05-15 08:21 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    """Check format and print news on console or json"""
Вот правильный вариант. Используйте его.
Но помимо описания того, что делает функция, еще принято описывать параметры фунции и возвращаемое значение.

2021-05-15 08:21 UTC, Shurke commented on tests/test.py
> +        self.assertTrue(parser.verbose)
Предыдущие замечания относительно тестов не были исправлены.

2021-05-17 15:23 UTC, Shurke commented
Проверка валидности лимита все так же остутствует.
![Screenshot from 2021-05-17 18-22-29](https://user-images.githubusercontent.com/44495358/118514036-e1d9cc00-b73c-11eb-9e35-d6df29051a81.png)

2021-05-17 17:26 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +
Вот эта часть может быть вынесена в отдельную функцию.

2021-05-17 17:26 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        args.limit = 50
А если придет больше новостей?

2021-05-17 17:26 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +            count += 1
Выгляди так, что данная часть кода не должна находиться внутри цикла `for` на 69 строке.

2021-05-17 17:26 UTC, Shurke commented on tests/test.py
> +        self.assertTrue(rss_reader.open_url(parser.url))
Выглядит так, что ваш тест ходит в интернет.
Так не должно быть, если мы говорим про юнит тесты.

2021-05-17 17:26 UTC, Shurke commented on tests/test.py
> +            parser = rss_reader.create_parser([None, "--version"])
Так же стоит рассмотреть случай, когда придет именно пустая строка.
`rss_reader ""`

2021-05-18 20:10 UTC, belovmd requested changes

2021-05-18 20:10 UTC, belovmd commented on rss_reader/__init__.py
> +from rss_reader import *
Why do we need `import *` here?
Can we avoid it?

2021-05-18 20:10 UTC, belovmd commented on tests/test.py
> +        """test positive limit"""
Sentences start with capital letter

2021-05-18 20:10 UTC, belovmd commented on tests/test.py
> +        """Test version with out url"""
without or w/o

2021-05-18 20:10 UTC, belovmd commented on tests/test.py
> +        self.assertTrue(parser.json)
It only checks that we have json and that's all.

2021-05-22 05:56 UTC, Shurke commented
При попытке запросить данные за вчера из ридера, ничего особо не получилось.
![Screenshot from 2021-05-22 08-55-06](https://user-images.githubusercontent.com/44495358/119216264-6f217580-badb-11eb-9c9b-0ca9761f580a.png)

2021-05-23 05:15 UTC, Shurke commented
`--json` не работает.
![Screenshot from 2021-05-23 08-14-20](https://user-images.githubusercontent.com/44495358/119249114-e835d100-bb9e-11eb-8b29-4ed6e116fca6.png)

2021-05-23 06:04 UTC, Shurke reviewed
Как глобальное замечание вынесу тот факт, что тесты сейчас написаны ради тестов.
И особого практического смысла не несут.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.date:
Стоит добавить проверку правильности вводимой даты.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    :param args from the user"""
Название функции не соответствует своему содержанию.
Именно к `print_news` относится
```python
        elif args.json:
            print(json.dumps(make_dict, indent=3))
            count += 1
        else:
            for name_of_line, news in make_dict.items():
                print(f"{name_of_line}: {news}")
                count += 1
```

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    from rss_reader.dataset import Data
Для чего нужен этот код?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +data = Data()
А с какой целью экземпляр создается здесь, а не в функции `print_news`?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +            f.close()
В чем заключается идея открыть и закрыть сражу же файл?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        with open("data.csv", "a") as f:
Вы открываете файл в `__init__` и открываете его еще раз здесь.
Не могу сказать, что это является правильным. 
Стоит изменить логику и выделить методы ответственные за чтение и запись в файл. И вызывать их в нужный момент.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        data.make_dataframe(data_)
Вы сначала собираете данные в словарь, после этого значения ключей словаря складываете в список, чтобы потом из списка эти данные снова поместить в словарь.
Почему в `data.make_dataframe()` не передать сразу словарь?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    make_dict = {}
Название переменной не несет никакого логического смысла.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        dict_ = dict()
Название переменной не несет никакого логического смысла.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        :param date=Date, limit=quantity news, verbose=if need log
Открыв `PEP8` и посмотрев раздел `Documentation Strings` можно найти ссылку на `PEP257 - Docstring Conventions`.
Я прикладываю обе ссылки на данные РЕР. Откройте их пожалуйста, прочтите и исправите строки документации в вашем проекте.
https://www.python.org/dev/peps/pep-0008/#documentation-strings
https://www.python.org/dev/peps/pep-0257/

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        for i in all_data:
Имя переменной `i` не несет никакого смысла.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +            sys.exit()
Вам не кажется странным, что сначала вы выведете на экран сообщения о том, что печатаете новость на дату, а потом что файл пустой?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +                print(f"Link : {link}\n")
А что мешает сразу подставлять в вывод на печать значения из словаря `self.data`?
```python
print(f"Title :{self.data['Title']}")
````

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +    from rss_reader.dataset import Data
Для чего этот код?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +    def test_init(self):
Из требований к проекту.

> Docstrings are mandatory for all methods, classes, functions and modules.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +        self.assertTrue(self.test)
Что тестирует данный тест?
И почему чуть ниже вы уже пишите `self.test = Data()`?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +            self.assertTrue(open("data.csv"))
Вы уверены что вам следует тестировать встроенную функцию Python `open()`?

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_rss_reader.py
> +        """Test version with out url"""
Вам уже оставляли комментарий о необходимости исправить `with out` на `without` или `w/o`.

2021-05-23 06:04 UTC, Shurke commented on rss_reader/tests/test_rss_reader.py
> +
Для чего здесь пустая строка?

2021-05-25 18:09 UTC, Shurke reviewed
Не устранены предыдущие замечания.

2021-05-26 16:46 UTC, SorryLegacy commented on rss_reader/rss_reader/rss_reader.py
> +    from rss_reader.dataset import Data
Чтоб программа не крашилась при активации через python rss_reader.py

2021-05-26 16:47 UTC, SorryLegacy commented on rss_reader/rss_reader/rss_reader.py
> +data = Data()
Есть снецарий при котором функция не вызывается

2021-05-26 16:47 UTC, SorryLegacy commented on rss_reader/rss_reader/rss_reader.py
> +    if args.date:
чуть ниже есть проверка

2021-05-27 06:06 UTC, Shurke commented
Task clarification (III)

> If --date specified together with RSS source, then app should get news for this date from local cache that were fetched from specified source.

![Screenshot from 2021-05-27 09-04-54](https://user-images.githubusercontent.com/44495358/119774343-b7210d80-beca-11eb-978a-b2b45f0e38af.png)

На скриншоте видно, что новость за 26 мая есть.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    from rss_reader.dataset import Data
Это показывает тот факт, что вы не понимаете, как работает импорт.
Ознакомитесь со статьей https://tproger.ru/translations/guide-into-python-imports/ и исправьте.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    if args.date:
Если придет дата `11111111`, то наверное стоит ее отсеивать.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +data = Data()
Тогда стоит рассмотреть вариант создания экземпляра в функции main и далее передавать его в нужные функции и уже там на месте вызывать нужные методы.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        data.make_csv()
Я думаю, что данным методом вы хотите открыть существующий файл, а не создать его.
Не очень удачное название метода.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +            print(json.dumps(feed["channel"]["title"], indent=3))
Я не думаю, что функции `print `нужно помещать в `try/except`.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +    def make_dataframe(self, item: {}):
Название метода не соответствует тому, что происходит внутри.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        with open("data.csv", "a") as f:
Все еще актуально.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    count = 0
А для чего нужен счетчик?

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +def parse_print_news(args):
Эта функция состоит из двух отельных:

- парсинг новостей и их обработка
- печать новостей

Стоит разнести их.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +    def print_data(self, date, limit, verbose, argjson):
По факту, у вас два различных метода, которые печатают новости.
Один из - кэша, второй - просто ленту.
Что выглядит не очень верным решением.
Стоит подумать над тем, чтобы из кэша забирать сохраненные данные и печать уже их какой-то единой функцией.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +                break
Очень костыльное решение.
Есть же цикл `while`.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +            self.test = Data()
Имя переменной не соответствует содержанию.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +class TestFile(unittest.TestCase):
Здесь не хватает тестов, которые проверяют правильную работу. Тестируются только негативные сценарии.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +class TestDataFrame(unittest.TestCase):
Смотрите замечание выше.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +class TestArg(unittest.TestCase):
У нас большее количество вариантов тестовых случаев для входных аргументов, чем представлено здесь.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_dataset.py
> +class Testinit(unittest.TestCase):
`TestInit`
Имя класса не несет никакого смысла о том, что в нем тестируется.

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_rss_reader.py
> +class TestProcessResponse(unittest.TestCase):
Здесь тестируется работа `argparse.ArgumentParser()`. Следовательно название должно это отражать.
Кроме того, у меня вопрос: для чего нужен класс `TestArg` из `rss_reader/tests/test_dataset.py`?

2021-05-27 06:35 UTC, Shurke commented on rss_reader/tests/test_rss_reader.py
> +class TestMain(unittest.TestCase):
При этом конкретная работа самого ридера у вас не тестируется.
И тесты частично повторяются с классом `TestProcessResponse`.

2021-05-28 15:17 UTC, SorryLegacy commented on rss_reader/rss_reader/rss_reader.py
> +    count = 0
Для логов

2021-05-29 10:48 UTC, Shurke commented
Третья итерация не работает.
<img width="1191" alt="Screenshot 2021-05-29 at 13 48 17" src="https://user-images.githubusercontent.com/44495358/120067482-8c7ab480-c084-11eb-93c5-9b3bd7c19bde.png">

2021-06-06 09:00 UTC, Shurke reviewed
Замечания в тестах проигнорированы.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    parser.add_argument("--date", type=str)
Стоит добавить секцию, которая поясняет принцип работы опции `--date`.
<img width="1276" alt="Screenshot 2021-06-06 at 11 35 51" src="https://user-images.githubusercontent.com/44495358/120918123-67f18e80-c6bb-11eb-8e8e-8eba651bd571.png">

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        sys.exit()
Лимит не должен влиять на сохранение новостей из rss-ленты в кеш.

<img width="834" alt="Screenshot 2021-06-06 at 11 38 18" src="https://user-images.githubusercontent.com/44495358/120918206-ddf5f580-c6bb-11eb-85ca-2081d8d9b80d.png">

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +            print_news(args, feed_news)
Эта часть никак не относится к `parse_news`.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    data.append_cache()
Если `args.url` будет пустым, то эта строка вызовется. Хотя, по идее не должна, т.к. нечего сохранять в кеш.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +                print(f"Link : {link}\n")
Очень странно, что у вас для печати новостей из кеша свой подход. 
Стоит рассмотреть вариант, при котором новости их любого источника будут печататься одинаково.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +        count += 1
Выглядит очень странным увеличение счетчика в двух местах.
```python
count += 1
logger.info(f"Process item № {count}")
````
Такой вариант выглядит проще для понимания.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +        with open("data.csv", "a") as f:
Если бы будете игнорировать комментарий, не означает, что он перестанет быть актуальным.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +                count += 1
Подобное замечание есть ниже.

2021-06-06 09:00 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +            sys.exit()
У вас лимит проверяется в нескольких местах.
Это не верно со стороны элементарной логики. Такие вещи следует проверять еще до начала работы приложения, после получения всех аргументов из командной строки.

2021-06-12 12:09 UTC, Shurke requested changes
При попытке конвертации в файл происходит падение ридера. 
![Screenshot 2021-06-12 at 15 08 57](https://user-images.githubusercontent.com/44495358/121775408-23209880-cb90-11eb-9164-5a36f5b1f072.png)

2021-06-12 12:09 UTC, Shurke commented on rss_reader/rss_reader/rss_reader.py
> +    parser.add_argument("-s", "--to-html", type=str, help="Converts news to HTML format", dest="to_html")
Стоит добавить явное описание того, как задавать путь к файлу для его конвертации.

2021-06-12 12:09 UTC, Shurke commented on rss_reader/rss_reader/dataset.py
> +            if int(date) == int(data[:10].replace('-', '')):
При обращении по дате и url, в данной строке происходит падение.
![Screenshot 2021-06-12 at 15 06 17](https://user-images.githubusercontent.com/44495358/121775365-cc1ac380-cb8f-11eb-915d-2fb852f5163d.png)

2021-06-19 12:12 UTC, Shurke commented
Общее замечание.
Строки документации носят номинальный характер. В достаточно большом количестве функций и тестов просто отсутствуют как таковые.
PEP257 обязателен для изучения.

2024-08-19 15:47 UTC, closed without merging